from py_slider import configure_styled_slider



def configure_sliders(self):

    configure_styled_slider(self.ui,
                            "Spikeling_Speed_slider",
                            groove_color="#586E75",
                            fill_color="#93A1A1",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")

    configure_styled_slider(self.ui,
            "Spikeling_StimFre_slider",
                          groove_color="#001E26",
                          fill_color="#268BD2",
                          num_ticks=11,
                          handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
            "Spikeling_StimStr_slider",
                          groove_color="#001E26",
                          fill_color="#268BD2",
                          num_ticks=11,
                          handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_PR_PhotoGain_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_PR_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_PR_Recovery_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")


    configure_styled_slider(self.ui,
                            "Spikeling_PatchClamp_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_Noise_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_Synapse1_slider",
                            groove_color="#001E26",
                            fill_color="#2AA198",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_Synapse1_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#2AA198",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_Synapse2_slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Spikeling_Synapse2_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")





    configure_styled_slider(self.ui,
                            "Emulator_Speed_slider",
                            groove_color="#586E75",
                            fill_color="#93A1A1",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")

    configure_styled_slider(self.ui,
                            "Emulator_StimFre_slider",
                            groove_color="#001E26",
                            fill_color="#268BD2",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_StimStrSlider",
                            groove_color="#001E26",
                            fill_color="#268BD2",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_PR_PhotoGain_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_PR_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_PR_Recovery_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")

    configure_styled_slider(self.ui,
                            "Emulator_PatchClamp_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Noise_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Synapse1_slider",
                            groove_color="#001E26",
                            fill_color="#2AA198",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Synapse1_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#2AA198",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Synapse2_slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Synapse2_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")

    configure_styled_slider(self.ui,
                            "Emulator_Syn1_PatchClamp_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn1_Noise_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn1_PR_PhotoGain_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn1_PR_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn1_PR_Recovery_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")

    configure_styled_slider(self.ui,
                            "Emulator_Syn2_PatchClamp_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn2_Noise_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn2_PR_PhotoGain_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn2_PR_Decay_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Emulator_Syn2_PR_Recovery_slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=15,
                            handle_image=":/resources/resources/Handle.png")





    configure_styled_slider(self.ui,
                            "Imaging_FrameRate_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_PMT_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_Laser_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")


    configure_styled_slider(self.ui,
                            "Imaging_CalciumRise_Slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_CalciumDecay_Slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_CalciumJump_Slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_CalciumNoise_Slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_CalciumBaseline_Slider",
                            groove_color="#001E26",
                            fill_color="#D33682",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")


    configure_styled_slider(self.ui,
                            "Imaging_IndRise_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_IndDecay_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_DFF_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_FluoScale_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_FluoOffset_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_FluoNoise_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_kd_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_Hill_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")
    configure_styled_slider(self.ui,
                            "Imaging_PhotoShotNoise_Slider",
                            groove_color="#001E26",
                            fill_color="#859900",
                            num_ticks=11,
                            handle_image=":/resources/resources/Handle.png")