M48
; DRILL file {KiCad 9.0.5} date 2026-01-02T16:31:20+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-02T16:31:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X157.11Y-55.05
X162.89Y-55.05
T2
X120.0Y-55.0
X120.0Y-110.0
X204.0Y-55.0
X204.0Y-110.0
M30
